
#pragma once

#define ING_GENERATE_NOP_DESTROY_FUNCTION_DEFINITION(TYPENAME) \
    inline void TYPENAME##_destroy(TYPENAME* val) {}

// will add more as needed
ING_GENERATE_NOP_DESTROY_FUNCTION_DEFINITION(char);
ING_GENERATE_NOP_DESTROY_FUNCTION_DEFINITION(int);
ING_GENERATE_NOP_DESTROY_FUNCTION_DEFINITION(unsigned);
ING_GENERATE_NOP_DESTROY_FUNCTION_DEFINITION(float);
ING_GENERATE_NOP_DESTROY_FUNCTION_DEFINITION(double);